services:

  mariadb:
    image: mariadb:lts
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql

  mailer:
    image: schickling/mailcatcher
    ports: ["1025:1025", "1080:1080"]

volumes:
  dbdata: